# Default values for atm-layer-mil-authenticator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: 00000000000.dkr.ecr.eu-south-1.amazonaws.com/xxxxxxx
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

namespace: pagopa

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

secretProviderClass:
  enabled: true
  name: atm-layer-mil-authenticator-secrets
  env: prod

milBasePath: https://mil-u-apim.azure-api.net

tracing:
  enabled: "true"
  endpointBasePath: "http://jaeger-collector.default.svc.cluster.local:4317"
  enableJDBCMonitoring: "true"

milAuthenticator:
  environment: prod
  executionMode: READ_WRITE
  logLevel: INFO
  applicationBasePath: /api/v1/mil-authenticator
  swaggerPath: /swagger-ui
  healthPath: /health/v1/mil-authenticator
  openapiPath: /health/v1/mil-authenticator

milAuth:
  clientCredentials: client_credentials
  credentialsSecretEnabled: true
  credentialsSecretName: "pagopa-prod-atm-layer-mil-authenticator-mil-auth"
  credentialsSecretKeys:
    clientId: CLIENT_ID
    clientSecret: CLIENT_SECRET

apiGatewayId: aw3zxm78qg
cognitoUserPoolId: eu-south-1_jN5nkKfcY

redis:
  credentialsSecretEnabled: true
  credentialsSecretName: "pagopa-prod-atm-layer-mil-authenticator-redis"
  credentialsSecretKeys:
    host: host
    port: port

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::00000000000:role/pagopa-prod-atm-layer-xxxxxx-serviceaccount-role
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: pagopa-prod-atm-layer-mil-authenticator

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

deployment:
  name: pagopa-prod-atm-layer-mil-authenticator
  annotations:
    reloader.stakater.com/auto: "true"
    secret.reloader.stakater.com/reload: pagopa-prod-atm-layer-mil-authenticator-redis, pagopa-prod-atm-layer-mil-authenticator-mil-auth

service:
  name: pagopa-prod-atm-layer-mil-authenticator
  type: NodePort
  port: 8080

ingress:
  enabled: false
  name: pagopa-prod-atm-layer-mil-authenticator
  className: ""
  annotations: 
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internal"
    alb.ingress.kubernetes.io/group.name: "alb-controller"
    alb.ingress.kubernetes.io/load-balancer-name: "pagopa-prod-atm-layer-alb-int"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTP": 8080}]'
  hosts:
    - host:
      paths:
        - path: /api/v1/mil-authenticator
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 150m
    memory: 200Mi
  requests:
    cpu: 30m
    memory: 80Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 40
  # targetMemoryUtilizationPercentage: 90

nodeSelector: {}

tolerations: []

affinity: {}

Release:
  Time:
    Seconds: 60
