apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass.name }}
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "pagopa-{{ .Values.secretProviderClass.env }}-atm-layer/redis/credentials"
          objectType: "secretsmanager"
          jmesPath: 
              - path: host
                objectAlias: REDIS_HOST
              - path: port
                objectAlias: REDIS_PORT
  secretObjects:
    - secretName: {{ .Values.redis.credentialsSecretName }}
      type: Opaque
      data:
        - objectName: "REDIS_HOST"  # reference the corresponding parameter
          key: {{ .Values.redis.credentialsSecretKeys.host }}
        - objectName: "REDIS_PORT"  # reference the corresponding parameter
          key: {{ .Values.redis.credentialsSecretKeys.port }}
